import type { ExecutionProfile } from "./shadow-router.js";

export const DEFAULT_SHADOW_PROFILES: ExecutionProfile[] = [
  { id: "gemini-flash-low", model: "ag/gemini-3.8-flash-low", enabled: true, profileClass: "general", hardCapabilities: { tools: true, vision: true }, taskFit: ["general", "transformation"], qualityTier: "cheap", costClass: "very_low", latencyClass: "fast", reasoningEffort: "low", supportedReasoningEfforts: ["minimal", "low"], defaultReasoningEffort: "low", maximumReasoningEffort: "low" },
  { id: "gemini-flash-medium", model: "ag/gemini-3.8-flash-medium", enabled: true, profileClass: "general", hardCapabilities: { tools: true, vision: true }, taskFit: ["general", "transformation", "code", "analysis", "research", "multimodal"], qualityTier: "balanced", costClass: "low", latencyClass: "fast", reasoningEffort: "medium", supportedReasoningEfforts: ["low", "medium", "high"], defaultReasoningEffort: "medium", maximumReasoningEffort: "high" },
  { id: "gemini-flash-high", model: "ag/gemini-3.8-flash-high", enabled: true, profileClass: "general", hardCapabilities: { tools: true, vision: true }, taskFit: ["general", "transformation", "code", "analysis", "research", "multimodal"], qualityTier: "strong", costClass: "medium", latencyClass: "medium", reasoningEffort: "high", supportedReasoningEfforts: ["low", "medium", "high"], defaultReasoningEffort: "high", maximumReasoningEffort: "high" },
  { id: "terra", model: "cx/gpt-5.6-terra", enabled: true, profileClass: "resilience", hardCapabilities: { tools: true, vision: true }, taskFit: ["general", "transformation", "code", "analysis", "research", "multimodal"], qualityTier: "strong", costClass: "high", latencyClass: "medium", reasoningEffort: "medium", supportedReasoningEfforts: ["low", "medium", "high"], defaultReasoningEffort: "medium", maximumReasoningEffort: "high" },
  { id: "sol", model: "cx/gpt-5.6-sol", enabled: false, profileClass: "general", hardCapabilities: { tools: true, vision: true }, taskFit: ["code", "analysis", "research"], qualityTier: "strong", costClass: "high", latencyClass: "slow", reasoningEffort: "high", supportedReasoningEfforts: ["medium", "high", "max"], defaultReasoningEffort: "high", maximumReasoningEffort: "max" },
  { id: "luna-review", model: "cx/gpt-5.6-luna-review", enabled: true, profileClass: "specialist", hardCapabilities: { tools: true, vision: true }, taskFit: ["analysis", "code"], qualityTier: "strong", costClass: "medium", latencyClass: "medium", reasoningEffort: "high", supportedReasoningEfforts: ["medium", "high"], defaultReasoningEffort: "high", maximumReasoningEffort: "high" },
  { id: "claude-sonnet", model: "ag/claude-sonnet-4-6", enabled: false, profileClass: "general", hardCapabilities: { tools: true, vision: true }, taskFit: ["general", "transformation", "code", "analysis", "research", "multimodal"], qualityTier: "strong", costClass: "high", latencyClass: "slow", reasoningEffort: "high", supportedReasoningEfforts: ["low", "medium", "high"], defaultReasoningEffort: "high", maximumReasoningEffort: "high" },
  { id: "claude-opus", model: "ag/claude-opus-4-6-thinking", enabled: false, profileClass: "general", hardCapabilities: { tools: true, vision: true }, taskFit: ["general", "transformation", "code", "analysis", "research", "multimodal"], qualityTier: "frontier", costClass: "very_high", latencyClass: "slow", reasoningEffort: "high", supportedReasoningEfforts: ["medium", "high", "max"], defaultReasoningEffort: "high", maximumReasoningEffort: "max" },
  { id: "astra", model: "cx/gpt-6-astra", enabled: false, profileClass: "general", hardCapabilities: { tools: true, vision: true }, taskFit: ["general", "transformation", "code", "analysis", "research", "multimodal"], qualityTier: "frontier", costClass: "very_high", latencyClass: "slow", reasoningEffort: "high", supportedReasoningEfforts: ["medium", "high", "max"], defaultReasoningEffort: "high", maximumReasoningEffort: "max" }
];
